############################################################
# Ping Identity
#
############################################################


global:
  image:
    tag: "edge"  # Uses images with the "edge" tag
    pullPolicy: Always

  ingress:
    addReleaseNameToHost: append
    defaultDomain: ping-devops.com
    annotations: 
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx-public"

pingaccess-admin:
  enabled: true
  privateCert:
    generate: true
  envs:
    SERVER_PROFILE_URL: https://github.com/chrisleggett/helm-clustering-sp.git
    SERVER_PROFILE_PATH: pingaccess
  container:
    waitFor:
      pingfederate-engine:
        service: https
        timeoutSeconds: 300
  ingress:
    enabled: false

pingaccess-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/chrisleggett/helm-clustering-sp.git
    SERVER_PROFILE_PATH: pingaccess
  ingress:
    enabled: true
    hosts:
      - host: pingaccess-engine._defaultDomain_
        paths:
        - path: /
          backend:
            serviceName: https

