############################################################
# Ping Identity
#
############################################################


global:
  image:
    tag: "edge"  # Uses images with the "edge" tag

pingaccess-admin:
  enabled: true
  privateCert:
    generate: true
  envs:
    SERVER_PROFILE_URL: https://github.com/chrisleggett/helm-clustering-sp.git
    SERVER_PROFILE_PATH: pingaccess
  container:
    waitFor:
      pingfederate-engine:
        service: https
        timeoutSeconds: 300

pingaccess-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/chrisleggett/helm-clustering-sp.git
    SERVER_PROFILE_PATH: pingaccess